# Generated by Django 4.1 on 2022-09-15 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadProduct_table",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50, unique=True)),
                (
                    "date_upload",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("product_picture", models.ImageField(upload_to="productImage/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
