# Generated by Django 4.1 on 2022-09-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadproduct_table",
            name="category",
            field=models.CharField(
                choices=[
                    ("---------", "--------"),
                    ("Fashion", "Fashion"),
                    ("Electronics", "Electronics"),
                    ("Computers", "Computers"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
