# Generated by Django 4.1 on 2022-09-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0002_uploadproduct_table_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadproduct_table",
            name="price",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="uploadproduct_table",
            name="quantity",
            field=models.CharField(max_length=11),
        ),
    ]
