# Generated by Django 4.1 on 2022-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0004_uploadproduct_table_approve_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadproduct_table",
            name="category",
            field=models.BooleanField(default=False),
        ),
    ]
