# Generated by Django 4.1 on 2022-09-22 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("productapp", "0006_uploadproduct_table_display_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_table",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "date_ordered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.CharField(max_length=11)),
                ("purchased", models.BooleanField(default=False)),
                ("delivered", models.BooleanField(default=False)),
                ("delivery_agent", models.IntegerField(null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productapp.uploadproduct_table",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
