# Generated by Django 4.1 on 2022-10-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice_table",
            name="delivery_agent",
            field=models.IntegerField(default=0),
        ),
    ]
