# Generated by Django 4.1 on 2022-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentapp", "0002_invoice_table_delivery_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice_table",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
    ]
